'use client';

/**
 * Demo deposit. Credits simulated balance only — the "address" shown is a
 * placeholder string generated by the backend for realism and is not a
 * blockchain address. Nothing sent to it would ever arrive anywhere.
 */
import { useEffect, useMemo, useState } from 'react';
import { useMutation, useQuery } from '@tanstack/react-query';
import { Check, Copy } from 'lucide-react';
import { AppShell, PageBody, PageHeader } from '@/components/layout/AppShell';
import { FeatureDisabledNotice, SimulationNotice } from '@/components/layout/DemoBadge';
import { usePlatform } from '@/components/providers';
import { useRefreshBalances } from '@/hooks/useSession';
import { api, errorMessage } from '@/lib/api';
import { assetLabel, cn, formatAmount, formatDateTime } from '@/lib/format';
import { AssetIcon } from '@/components/AssetIcon';
import { FormError, Input } from '@/components/ui/form';
import { useToast } from '@/components/ui/toast';
import {
  Badge,
  Button,
  Card,
  CardBody,
  CardHeader,
  DataRow,
  Divider,
  ErrorState,
  Skeleton,
} from '@/components/ui/primitives';

interface DepositOption {
  asset: string;
  label: string;
  decimals: number;
  icon: string | null;
  market: string | null;
}

interface AssetListResponse {
  assets: DepositOption[];
  quoteAsset: string;
  note: string;
}

interface DemoDeposit {
  id: string;
  asset: string;
  amount: string;
  status: string;
  reference: string;
  simulatedAddress: string;
  createdAt: string;
  message?: string | null;
}

export default function DepositPage() {
  const { config } = usePlatform();
  const toast = useToast();
  const refreshBalances = useRefreshBalances();

  const [asset, setAsset] = useState('');
  const [amount, setAmount] = useState('');
  const [amountError, setAmountError] = useState<string | null>(null);
  const [formError, setFormError] = useState<string | null>(null);
  const [copied, setCopied] = useState(false);
  const [receipt, setReceipt] = useState<DemoDeposit | null>(null);

  const options = useQuery({
    queryKey: ['deposit-assets'],
    queryFn: () => api.get<AssetListResponse>('/assets'),
    enabled: config.depositsEnabled,
  });

  const assets = useMemo(() => options.data?.assets ?? [], [options.data]);
  const selected = assets.find((item) => item.asset === asset) ?? assets[0] ?? null;

  useEffect(() => {
    if (!asset && assets.length > 0) setAsset(assets[0].asset);
  }, [asset, assets]);

  useEffect(() => {
    setCopied(false);
  }, [receipt?.simulatedAddress]);

  const mutation = useMutation({
    mutationFn: (body: { asset: string; amount: string }) =>
      api.post<DemoDeposit>('/deposits/demo', body),
    onSuccess: (data) => {
      setReceipt(data);
      setAmount('');
      refreshBalances();
      toast.success('Demo deposit created', `Reference ${data.reference}`);
    },
    onError: (error) => setFormError(errorMessage(error)),
  });

  const validate = (): string | null => {
    if (!selected) return 'Select an asset first.';
    const parsed = Number(amount);
    if (!amount.trim() || !Number.isFinite(parsed) || parsed <= 0) {
      return 'Enter an amount greater than zero.';
    }
    return null;
  };

  const submit = () => {
    setFormError(null);
    const problem = validate();
    setAmountError(problem);
    if (problem || !selected) return;
    mutation.mutate({ asset: selected.asset, amount: amount.trim() });
  };

  const copyAddress = async () => {
    if (!receipt) return;
    try {
      await navigator.clipboard.writeText(receipt.simulatedAddress);
      setCopied(true);
      toast.success('Simulated address copied');
    } catch {
      toast.error('Could not copy', 'Select the address and copy it manually.');
    }
  };

  return (
    <AppShell hideBottomNav>
      <PageHeader title="Deposit" backHref="/assets" />
      <PageBody>
        {!config.depositsEnabled ? (
          <FeatureDisabledNotice message="Demo deposits are currently unavailable." />
        ) : options.isLoading ? (
          <div className="space-y-3">
            <Skeleton className="h-24 w-full" />
            <Skeleton className="h-32 w-full" />
          </div>
        ) : options.isError ? (
          <ErrorState
            title="Could not load deposit assets"
            description={errorMessage(options.error)}
            onRetry={() => void options.refetch()}
          />
        ) : (
          <div className="space-y-4">
            <SimulationNotice tone="warning">
              <strong className="font-bold uppercase tracking-wide">
                Simulation only — no real blockchain transfer.
              </strong>{' '}
              This screen credits simulated demo balance instantly. The address shown on the
              receipt is a placeholder for the demo interface. Never send real cryptocurrency to
              it — it belongs to no wallet and any funds would be lost.
            </SimulationNotice>

            <Card>
              <CardHeader title="Asset" description="Choose which demo asset to credit." />
              <CardBody className="pt-3">
                <div
                  role="radiogroup"
                  aria-label="Deposit asset"
                  className="grid grid-cols-1 gap-2 sm:grid-cols-3"
                >
                  {assets.map((item) => {
                    const active = selected?.asset === item.asset;
                    return (
                      <button
                        key={item.asset}
                        type="button"
                        role="radio"
                        aria-checked={active}
                        onClick={() => setAsset(item.asset)}
                        className={cn(
                          'touch-target flex items-center gap-2.5 rounded-control border px-3 text-left transition-colors',
                          active
                            ? 'border-primary bg-primary/10 text-fg'
                            : 'border-border bg-surface text-muted hover:text-fg',
                        )}
                      >
                        <AssetIcon asset={item.asset} size="sm" />
                        <span className="min-w-0 flex-1 truncate text-sm font-medium">
                          {item.label || assetLabel(item.asset)}
                        </span>
                        {active && <Check className="h-4 w-4 text-primary" aria-hidden />}
                      </button>
                    );
                  })}
                </div>
              </CardBody>
            </Card>

            {receipt && (
              <Card>
                <CardHeader
                  title="Simulated deposit address"
                  description="Demo placeholder — not a blockchain address"
                  action={<Badge tone="warning">Not a real address</Badge>}
                />
                <CardBody className="pt-3">
                  <p className="break-all rounded-control bg-surface px-3 py-3 font-mono text-xs text-fg">
                    {receipt.simulatedAddress}
                  </p>
                  <Button
                    variant="outline"
                    fullWidth
                    className="mt-3"
                    onClick={() => void copyAddress()}
                    aria-label="Copy simulated deposit address"
                  >
                    {copied ? (
                      <Check className="h-4 w-4" aria-hidden />
                    ) : (
                      <Copy className="h-4 w-4" aria-hidden />
                    )}
                    {copied ? 'Copied' : 'Copy address'}
                  </Button>
                </CardBody>
              </Card>
            )}

            <Card>
              <CardBody className="space-y-4">
                <Input
                  label="Amount"
                  inputMode="decimal"
                  type="number"
                  min="0"
                  step="any"
                  placeholder="0.00"
                  value={amount}
                  error={amountError}
                  hint={
                    selected
                      ? `Simulated ${assetLabel(selected.asset)} credited to your demo balance.`
                      : undefined
                  }
                  onChange={(event) => {
                    setAmount(event.target.value);
                    if (amountError) setAmountError(null);
                  }}
                />
                <FormError message={formError} />
                <Button
                  fullWidth
                  size="lg"
                  loading={mutation.isPending}
                  disabled={!selected}
                  onClick={submit}
                >
                  Generate Demo Deposit
                </Button>
                <p className="text-center text-xs text-muted">
                  Demo deposit only. No blockchain transaction will be created.
                </p>
              </CardBody>
            </Card>

            {receipt && (
              <Card>
                <CardHeader title="Demo deposit created" />
                <CardBody className="pt-1">
                  <DataRow label="Reference" value={receipt.reference} tone="strong" />
                  <Divider />
                  <DataRow label="Status" value={<Badge tone="success">{receipt.status}</Badge>} />
                  <Divider />
                  <DataRow
                    label="Amount"
                    value={`${formatAmount(receipt.amount, 2)} ${assetLabel(receipt.asset)}`}
                  />
                  <Divider />
                  <DataRow label="Created" value={formatDateTime(receipt.createdAt)} />
                </CardBody>
              </Card>
            )}
          </div>
        )}
      </PageBody>
    </AppShell>
  );
}
